### ISSUE TITLE
why it happen?

### ISSUE THREAD

**Issue by songyiren98** [Picsart-AI-Research/LIVE-Layerwise-Image-Vectorization#1]
Input image shape is: (240, 240, 3)
=> Adding [1] paths, [circle] ...
Segmentation fault (core dumped)

**Comment by ma-xu** [comment]
@songyiren98  One of the possible reasons is the version of opencv. 
pip install opencv-python==4.5.4.60  # please install this version to avoid segmentation fault.

Could you please double-check the version? If it still does not work, could you please post your environments (like cuda, pytorch, etc) so that I help debug this problem?

**Comment by songyiren98** [comment]
Thank you very much, I will check it.

**Comment by ma-xu** [comment]
@songyiren98  I will close this issue since no further discussions. Feel free to re-open it if necessary.
